name: verify-build-publish

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  security-events: write

jobs:
  java:
    uses: cantalay/talay-workflows/.github/workflows/java.yaml@804711925abc685d4f5e48aed1ced1a95b9041e7
    with:
      java-version: "17"
      build-tool: maven
      image-name: ghcr.io/cantalay/auth-gateway
      push-image: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      upload-sarif: false
