name: verify-build-publish

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  security-events: write

jobs:
  java:
    uses: cantalay/talay-workflows/.github/workflows/java.yaml@6a53c09e82e4a4f5311ea65b5e04d2e81c8381fc
    with:
      java-version: "17"
      build-tool: maven
      image-name: ghcr.io/cantalay/todogi-auth-gateway
      push-image: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      upload-sarif: false
